antiblocks:
  - REDSTONE
  - REDSTONE_TORCH
  - REDSTONE_BLOCK
  - REDSTONE_BLOCK
  - REDSTONE_WALL_TORCH
  - TRAPPED_CHEST
  - DETECTOR_RAIL
  - COMPARATOR
  - TARGET
  - OBSERVER
  - TRIPWIRE_HOOK
  - TRIPWIRE